<Project>
    <!-- language configs -->
    <PropertyGroup>
        <LangVersion>14.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <!-- package configs -->
    <PropertyGroup>
        <Authors>aka-nse</Authors>
        <PackageProjectUrl>https://github.com/aka-nse/RunaString</PackageProjectUrl>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/aka-nse/RunaString</RepositoryUrl>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>
</Project>
