<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>14.0</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
      <None Include="RunaUtf8InterpolationHandlerTest.AutoGen.g.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>RunaUtf8InterpolationHandlerTest.AutoGen.tt</DependentUpon>
      </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\RunaString\RunaString.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
      <None Update="RunaUtf8InterpolationHandlerTest.AutoGen.tt">
        <Generator>TextTemplatingFileGenerator</Generator>
        <LastGenOutput>RunaUtf8InterpolationHandlerTest.AutoGen.g.cs</LastGenOutput>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="RunaUtf8InterpolationHandlerTest.AutoGen.g.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>RunaUtf8InterpolationHandlerTest.AutoGen.tt</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
